### ISSUE TITLE
Comment about 32-bit tclkit seems redundant as 64-bit installers bitrock installers exist

### ISSUE THREAD

**Issue by jose1711** [greyltc/bitrock-unpacker#1]
https://github.com/greyltc/bitrock-unpacker/blob/84d9a1480ccd77e5d82d0356155b727c8e6ad542/bitrock-unpacker.tcl#L4

I find this unnecessary as I was able to use this to extract `zoiper-classic` installer with 64-bit `tclkit` just fine.

**Comment by greyltc** [comment]
soved by https://github.com/greyltc/bitrock-unpacker/commit/910499f20f760d49c36ce7b5d534b0ac004d1a08
